version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: study_agency
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  backend:
    build:
      context: .
    container_name: my-backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - my-network

  frontend:
    build:
      context: ../frontend
    container_name: my-frontend
    ports:
      - "80:80"
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
